import type { Activity, Client, Deal, IntegrationDemo, Lead, Task, TeamMember } from './types'

export const team: TeamMember[] = [
  { id: 'tm-1', name: 'Karan Mehta', role: 'Owner', email: 'karan@kmaxdesign.com' },
  { id: 'tm-2', name: 'Aisha Rao', role: 'Product strategist', email: 'aisha@kmaxdesign.com' },
  { id: 'tm-3', name: 'Rohan Singh', role: 'Developer', email: 'rohan@kmaxdesign.com' },
]

export const leads: Lead[] = [
  {
    id: 'lead-1',
    name: 'Priya Shah',
    email: 'priya@novalaunch.io',
    company: 'NovaLaunch Labs',
    source: 'Website form',
    serviceType: 'AI MVP build',
    budgetRange: '$8k-$12k',
    estimatedValue: 10800,
    timeline: '6 weeks',
    projectSummary: 'AI platform that turns customer interviews into product insights and roadmap recommendations.',
    status: 'Qualified',
    qualityScore: 92,
    riskLevel: 'Low',
    ownerId: 'tm-1',
    nextFollowUpDate: '2026-06-03',
    lastContactDate: '2026-06-01',
    createdAt: '2026-05-27',
  },
  {
    id: 'lead-2',
    name: 'Omar Blake',
    email: 'omar@brightcart.studio',
    company: 'BrightCart Studio',
    source: 'Referral',
    serviceType: 'Internal dashboard',
    budgetRange: '$5k-$8k',
    estimatedValue: 7200,
    timeline: '4 weeks',
    projectSummary: 'Inventory and campaign performance dashboard for a small ecommerce team.',
    status: 'Converted',
    qualityScore: 81,
    riskLevel: 'Low',
    ownerId: 'tm-2',
    nextFollowUpDate: '2026-06-04',
    lastContactDate: '2026-06-02',
    createdAt: '2026-05-23',
  },
  {
    id: 'lead-3',
    name: 'Neel Verma',
    email: 'neel@mentordesk.co',
    company: 'MentorDesk',
    source: 'LinkedIn',
    serviceType: 'Marketplace MVP',
    budgetRange: '$12k-$18k',
    estimatedValue: 15600,
    timeline: '8 weeks',
    projectSummary: 'Expert marketplace for founders to book paid strategy sessions with verified operators.',
    status: 'Qualified',
    qualityScore: 88,
    riskLevel: 'Medium',
    ownerId: 'tm-1',
    nextFollowUpDate: '2026-06-05',
    lastContactDate: '2026-05-31',
    createdAt: '2026-05-20',
  },
  {
    id: 'lead-4',
    name: 'Maya Chen',
    email: 'maya@creatoros.app',
    company: 'CreatorOS',
    source: 'X/Twitter',
    serviceType: 'Creator SaaS',
    budgetRange: '$3k-$5k',
    estimatedValue: 4200,
    timeline: 'Not clear',
    projectSummary: 'Creator subscription hub with content scheduling, member perks, and simple analytics.',
    status: 'Contacted',
    qualityScore: 58,
    riskLevel: 'High',
    ownerId: 'tm-2',
    nextFollowUpDate: '2026-06-02',
    lastContactDate: '2026-05-29',
    createdAt: '2026-05-29',
  },
  {
    id: 'lead-5',
    name: 'Kabir Sethi',
    email: 'kabir@pixelforge.agency',
    company: 'PixelForge Agency',
    source: 'Partner referral',
    serviceType: 'Product partner retainer',
    budgetRange: '$4k/month',
    estimatedValue: 12000,
    timeline: 'Ongoing',
    projectSummary: 'Monthly product development support for agency clients that need MVP and dashboard builds.',
    status: 'Qualified',
    qualityScore: 95,
    riskLevel: 'Low',
    ownerId: 'tm-1',
    nextFollowUpDate: '2026-06-03',
    lastContactDate: '2026-06-02',
    createdAt: '2026-05-18',
  },
  {
    id: 'lead-6',
    name: 'Sana Ali',
    email: 'sana@opsbridge.ai',
    company: 'OpsBridge AI',
    source: 'Cold outreach',
    serviceType: 'AI workflow automation',
    budgetRange: '$6k-$9k',
    estimatedValue: 8500,
    timeline: '5 weeks',
    projectSummary: 'Automation layer that routes inbound support tickets and drafts internal response notes.',
    status: 'New',
    qualityScore: 76,
    riskLevel: 'Medium',
    ownerId: 'tm-3',
    nextFollowUpDate: '2026-06-06',
    lastContactDate: '2026-05-30',
    createdAt: '2026-05-30',
  },
  {
    id: 'lead-7',
    name: 'Ethan Morris',
    email: 'ethan@legacycrm.co',
    company: 'LegacyCRM Co',
    source: 'Community',
    serviceType: 'Product redesign',
    budgetRange: '$1k-$2k',
    estimatedValue: 1800,
    timeline: 'ASAP',
    projectSummary: 'A rushed CRM redesign request with unclear scope, no decision maker, and a low launch budget.',
    status: 'Unqualified',
    qualityScore: 32,
    riskLevel: 'High',
    ownerId: 'tm-2',
    nextFollowUpDate: '2026-05-28',
    lastContactDate: '2026-05-26',
    createdAt: '2026-05-25',
  },
]

export const deals: Deal[] = [
  {
    id: 'deal-1',
    leadId: 'lead-1',
    title: 'NovaLaunch AI insight MVP',
    stage: 'Qualified',
    value: 10800,
    probability: 0.65,
    proposalStatus: 'Draft',
    expectedCloseDate: '2026-06-12',
    ownerId: 'tm-1',
    notes: 'Strong fit. Needs a clear phased scope and prototype-first plan.',
    updatedAt: '2026-06-02',
  },
  {
    id: 'deal-2',
    leadId: 'lead-2',
    title: 'BrightCart ops dashboard',
    stage: 'Proposal Sent',
    value: 7200,
    probability: 0.55,
    proposalStatus: 'Sent',
    expectedCloseDate: '2026-06-10',
    ownerId: 'tm-2',
    notes: 'Decision depends on dashboard reporting scope.',
    updatedAt: '2026-06-01',
  },
  {
    id: 'deal-3',
    leadId: 'lead-3',
    title: 'MentorDesk marketplace MVP',
    stage: 'Negotiation',
    value: 15600,
    probability: 0.72,
    proposalStatus: 'Viewed',
    expectedCloseDate: '2026-06-18',
    ownerId: 'tm-1',
    notes: 'Client asked for payment and calendar sync as v2 modules.',
    updatedAt: '2026-06-02',
  },
  {
    id: 'deal-4',
    leadId: 'lead-4',
    title: 'CreatorOS subscription hub',
    stage: 'New Lead',
    value: 4200,
    probability: 0.25,
    proposalStatus: 'Not started',
    expectedCloseDate: '2026-06-28',
    ownerId: 'tm-2',
    notes: 'Budget low and timeline unclear. Needs paid discovery first.',
    updatedAt: '2026-05-30',
  },
  {
    id: 'deal-5',
    leadId: 'lead-5',
    title: 'PixelForge product retainer',
    stage: 'Won',
    value: 11800,
    probability: 1,
    proposalStatus: 'Accepted',
    expectedCloseDate: '2026-06-01',
    ownerId: 'tm-1',
    notes: 'Won. Handoff and onboarding checklist created.',
    updatedAt: '2026-06-01',
  },
  {
    id: 'deal-6',
    leadId: 'lead-6',
    title: 'OpsBridge ticket automation',
    stage: 'New Lead',
    value: 8500,
    probability: 0.35,
    proposalStatus: 'Not started',
    expectedCloseDate: '2026-06-22',
    ownerId: 'tm-3',
    notes: 'Good pain point, needs technical discovery.',
    updatedAt: '2026-05-31',
  },
  {
    id: 'deal-7',
    leadId: 'lead-7',
    title: 'LegacyCRM rush redesign',
    stage: 'Lost',
    value: 1800,
    probability: 0,
    proposalStatus: 'Rejected',
    expectedCloseDate: '2026-05-30',
    ownerId: 'tm-2',
    notes: 'Marked lost because budget, timeline, and scope were not viable for a serious MVP engagement.',
    updatedAt: '2026-05-28',
  },
]

export const tasks: Task[] = [
  { id: 'task-1', relatedType: 'Deal', relatedId: 'deal-1', title: 'Send revised MVP phase options', dueDate: '2026-06-03', priority: 'High', status: 'Open', ownerId: 'tm-1' },
  { id: 'task-2', relatedType: 'Deal', relatedId: 'deal-2', title: 'Follow up on analytics scope approval', dueDate: '2026-06-04', priority: 'Medium', status: 'Open', ownerId: 'tm-2' },
  { id: 'task-3', relatedType: 'Lead', relatedId: 'lead-4', title: 'Recommend paid discovery before build quote', dueDate: '2026-06-02', priority: 'High', status: 'Overdue', ownerId: 'tm-2' },
  { id: 'task-4', relatedType: 'Client', relatedId: 'client-1', title: 'Prepare kickoff asset checklist', dueDate: '2026-06-03', priority: 'High', status: 'Open', ownerId: 'tm-1' },
  { id: 'task-5', relatedType: 'Lead', relatedId: 'lead-6', title: 'Book technical workflow audit call', dueDate: '2026-06-06', priority: 'Medium', status: 'Open', ownerId: 'tm-3' },
  { id: 'task-6', relatedType: 'Deal', relatedId: 'deal-3', title: 'Clarify calendar integration as v2 item', dueDate: '2026-06-05', priority: 'Medium', status: 'Open', ownerId: 'tm-1' },
]

export const clients: Client[] = [
  { id: 'client-1', name: 'Kabir Sethi', company: 'PixelForge Agency', email: 'kabir@pixelforge.agency', status: 'Onboarding', totalRevenue: 11800, activeProjects: 1, ownerId: 'tm-1' },
  { id: 'client-2', name: 'Leah Brown', company: 'Atlas Growth', email: 'leah@atlasgrowth.co', status: 'Active', totalRevenue: 9600, activeProjects: 2, ownerId: 'tm-2' },
  { id: 'client-3', name: 'Arjun Nair', company: 'SprintStack', email: 'arjun@sprintstack.io', status: 'Past', totalRevenue: 6800, activeProjects: 0, ownerId: 'tm-3' },
]

export const activity: Activity[] = [
  { id: 'act-1', relatedId: 'deal-5', actor: 'Karan', message: 'Marked PixelForge retainer as won and started handoff.', createdAt: 'Today, 10:20 AM' },
  { id: 'act-2', relatedId: 'deal-3', actor: 'Aisha', message: 'Added negotiation note about calendar sync moving to v2.', createdAt: 'Today, 9:42 AM' },
  { id: 'act-3', relatedId: 'lead-1', actor: 'Pipeline AI', message: 'Flagged NovaLaunch as high-quality lead with low scope risk.', createdAt: 'Yesterday, 4:15 PM' },
  { id: 'act-4', relatedId: 'deal-2', actor: 'Rohan', message: 'Attached technical estimate for reporting module.', createdAt: 'Yesterday, 2:30 PM' },
]

export const sourceData = [
  { name: 'Website', leads: 18, won: 5 },
  { name: 'Referral', leads: 14, won: 7 },
  { name: 'LinkedIn', leads: 12, won: 4 },
  { name: 'Outreach', leads: 9, won: 2 },
  { name: 'Community', leads: 7, won: 1 },
]

export const revenueTrend = [
  { month: 'Jan', pipeline: 18000, won: 7200 },
  { month: 'Feb', pipeline: 22000, won: 8600 },
  { month: 'Mar', pipeline: 26000, won: 10400 },
  { month: 'Apr', pipeline: 31000, won: 9800 },
  { month: 'May', pipeline: 40500, won: 11800 },
  { month: 'Jun', pipeline: 48500, won: 14200 },
]

export const integrationDemos: IntegrationDemo[] = [
  {
    id: 'int-email',
    name: 'Gmail lead capture',
    category: 'Email',
    status: 'Connected',
    description: 'Turns inbound inquiry emails into lead drafts with source, budget, service type, and next action.',
    sampleEvent: 'New email from founder@northstar.ai asking for an AI dashboard quote.',
    result: 'Lead draft created with AI dashboard service, medium priority, and follow-up due tomorrow.',
  },
  {
    id: 'int-calendar',
    name: 'Calendar follow-up booking',
    category: 'Calendar',
    status: 'Ready to connect',
    description: 'Creates a calendar hold when a follow-up task is scheduled from the Follow-ups page.',
    sampleEvent: 'NovaLaunch follow-up scheduled for 2026-06-04.',
    result: '30-minute discovery follow-up prepared with owner, client email, and deal context.',
  },
  {
    id: 'int-alert',
    name: 'Slack and WhatsApp alerts',
    category: 'Alert',
    status: 'Needs review',
    description: 'Sends team alerts for overdue follow-ups, high-fit leads, and stuck proposal-stage deals.',
    sampleEvent: 'CreatorOS is overdue and has high scope risk.',
    result: 'Owner alert drafted with risk reason, recommended paid discovery, and direct lead link.',
  },
  {
    id: 'int-webhook',
    name: 'Won deal webhook',
    category: 'Webhook',
    status: 'Connected',
    description: 'Pushes won-deal data into a delivery board or project management tool after handoff starts.',
    sampleEvent: 'PixelForge product retainer moved to Won.',
    result: 'Project payload prepared with kickoff checklist, delivery owner, budget, and milestone template.',
  },
]
